services:
  php-app:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php_app_cs
    ports:
      - "8080:80"
    volumes:
      - ./php/src:/var/www/html
    networks:
      - app-network

  python-api:
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: python_api_cs
    ports:
      - "8000:8000"
    volumes:
      - ./python/src:/app
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql_db_cs
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge