
services:
  php-app:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php_app_cs
    ports:
      - "8080:80"
    volumes:
      - ./php/src:/var/www/html
    networks:
      - app-network

  # Serviço Python
  python-api:
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: python_api_cs
    ports:
      - "8000:8000"
    volumes:
      - ./python/src:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge